# Generated by Django 4.2.1 on 2023-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_book_edition_alter_book_authour_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="authour",
            new_name="author",
        ),
    ]
