# Generated by Django 4.2.1 on 2023-06-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_authour_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fine",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="fine",
            name="book",
        ),
        migrations.AddField(
            model_name="fine",
            name="fine_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fine",
            name="status",
            field=models.CharField(
                choices=[("OVERDUE", "Overdue"), ("PAID", "Paid")],
                default="OVERDUE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BorrowedBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("borrowed_date", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("BORROWED", "Borrowed"), ("RETURNED", "Returned")],
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fine",
            name="borrowed_book",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.borrowedbook",
            ),
        ),
    ]
