# Generated by Django 4.2.1 on 2023-06-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_fine_amount_remove_fine_book_fine_fine_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="borrowed_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.borrowedbook"
            ),
        ),
    ]
